insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z23W','zkdwxMaster_Add_Group','',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',1,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z23X','Add','新增',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',2,'general_btn','common','zkdwxMaster_Add_Group',null,'Ctrl+/','button_main',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z23Y','Edit','修改',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',3,'general_btn','common','zkdwxMaster_Add_Group',null,'Alt+P','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z23Z','Copy','复制',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',4,'general_btn','common','zkdwxMaster_Add_Group',null,'Alt+C','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z240','Delete','删除',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',5,'general_btn','common','zkdwxMaster_Add_Group',null,'Ctrl+Del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z241','zkdwxMaster_Save_Group','',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',6,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z242','Save','保存',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',7,'general_btn','common','zkdwxMaster_Save_Group',null,'Ctrl+S','button_main',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z243','SaveAdd','保存新增',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',8,'general_btn','common','zkdwxMaster_Save_Group',null,'Alt+S','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z244','Cancel','取消',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',9,'general_btn','common',null,null,'Alt+Q','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z245','zkdwxSlave0_AddLine_Group','',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',10,'buttongroup','zkdwxSlave0Sub',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z246','zkdwxSlave0Sub_AddLine','增行',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',11,'general_btn','zkdwxSlave0Sub','zkdwxSlave0_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z247','zkdwxSlave0Sub_CopyLine','复制',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',12,'general_btn','zkdwxSlave0Sub','zkdwxSlave0_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z248','zkdwxSlave0Sub_DelLine','删行',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',13,'general_btn','zkdwxSlave0Sub','zkdwxSlave0_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z249','zkdwxSlave0_Past_Group','',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',14,'buttongroup','zkdwxSlave0Sub',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z24A','zkdwxSlave0Sub_PastEndLine','粘贴到末行',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',15,'general_btn','zkdwxSlave0Sub','zkdwxSlave0_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z24B','zkdwxSlave0Sub_CopyCancelLine','取消',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',16,'general_btn','zkdwxSlave0Sub','zkdwxSlave0_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z24C','zkdwxSlave0Sub_DelLineOpr','删除',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',17,'general_btn','zkdwxSlave0SubOpr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z24D','zkdwxSlave0Sub_ExpandLineOpr','展开',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',18,'general_btn','zkdwxSlave0SubOpr',null,null,'f4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z24E','zkdwxSlave0Sub_CopyLineOpr','复制行',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',19,'general_btn','zkdwxSlave0SubOpr',null,null,'Alt+C','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z24F','zkdwxSlave0Sub_PastNextLineOpr','粘贴至此',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',20,'general_btn','zkdwxSlave0SubOpr',null,null,'alt+v','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001Z24G','Refresh','',null,null,'1001ZZ1000000001Z1VR',null,'Y','80H25001_zkdwxMaster',21,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

