insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETG9','dbsqMaster_Add_Group','',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',1,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGA','Add','新增',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',2,'general_btn','common','dbsqMaster_Add_Group',null,'Ctrl+/','button_main',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGB','Edit','修改',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',3,'general_btn','common','dbsqMaster_Add_Group',null,'Alt+P','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGC','Copy','复制',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',4,'general_btn','common','dbsqMaster_Add_Group',null,'Alt+C','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGD','Delete','删除',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',5,'general_btn','common','dbsqMaster_Add_Group',null,'Ctrl+Del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGE','dbsqMaster_Save_Group','',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',6,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGF','Save','保存',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',7,'general_btn','common','dbsqMaster_Save_Group',null,'Ctrl+S','button_main',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGG','SaveAdd','保存新增',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',8,'general_btn','common','dbsqMaster_Save_Group',null,'Alt+S','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGH','Cancel','取消',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',9,'general_btn','common',null,null,'Alt+Q','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGI','dbsqSlave0_AddLine_Group','',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',10,'buttongroup','dbsqSlave0Sub',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGJ','dbsqSlave0Sub_AddLine','增行',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',11,'general_btn','dbsqSlave0Sub','dbsqSlave0_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGK','dbsqSlave0Sub_CopyLine','复制',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',12,'general_btn','dbsqSlave0Sub','dbsqSlave0_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGL','dbsqSlave0Sub_DelLine','删行',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',13,'general_btn','dbsqSlave0Sub','dbsqSlave0_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGM','dbsqSlave0_Past_Group','',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',14,'buttongroup','dbsqSlave0Sub',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGN','dbsqSlave0Sub_PastEndLine','粘贴到末行',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',15,'general_btn','dbsqSlave0Sub','dbsqSlave0_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGO','dbsqSlave0Sub_CopyCancelLine','取消',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',16,'general_btn','dbsqSlave0Sub','dbsqSlave0_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGP','dbsqSlave0Sub_DelLineOpr','删除',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',17,'general_btn','dbsqSlave0SubOpr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGQ','dbsqSlave0Sub_ExpandLineOpr','展开',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',18,'general_btn','dbsqSlave0SubOpr',null,null,'f4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGR','dbsqSlave0Sub_CopyLineOpr','复制行',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',19,'general_btn','dbsqSlave0SubOpr',null,null,'Alt+C','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGS','dbsqSlave0Sub_PastNextLineOpr','粘贴至此',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',20,'general_btn','dbsqSlave0SubOpr',null,null,'alt+v','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002ETGT','Refresh','',null,null,'1001A11000000002ET8V',null,'Y','80H55001_dbsqMaster',21,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

