insert into BD_REFINFO ( CODE,ISTREELAZYLOAD,ISNEEDPARA,ISSPECIALREF,LAYER,REFTYPE,METADATANAMESPACE,METADATATYPENAME,MOBILEREFPATH,MODULENAME,NAME,PARA1,PARA2,PARA3,PK_COUNTRY,PK_INDUSTRY,PK_REFINFO,REFCLASS,REFPATH,REFSYSTEM,RESERV1,RESERV2,RESERV3,RESID,RESIDPATH,WHEREPART,WORKFLOWCONDITIONUSEUNITORG,TS,DR ) values  ( '80H35001','N',null,null,null,0,'gxbg','gxbgMaster',null,'wsh','工序报工_工序报工主实体_默认表参照_gxbg_gxbgMaster',null,null,null,null,null,'1001A11LCP000002UCMI',null,'wsh/refer/gxbg/gxbgMasterDefaultGridRef/index',null,null,null,null,'gxbg','gxbg',null,null,'2023-07-28 10:51:41',0 ) 
/

