insert into BD_REFINFO ( CODE,ISTREELAZYLOAD,ISNEEDPARA,ISSPECIALREF,LAYER,REFTYPE,METADATANAMESPACE,METADATATYPENAME,MOBILEREFPATH,MODULENAME,NAME,PARA1,PARA2,PARA3,PK_COUNTRY,PK_INDUSTRY,PK_REFINFO,REFCLASS,REFPATH,REFSYSTEM,RESERV1,RESERV2,RESERV3,RESID,RESIDPATH,WHEREPART,WORKFLOWCONDITIONUSEUNITORG,TS,DR ) values  ( '80H37001','N',null,null,null,0,'gxth','gxthMaster',null,'wsh','工序退回_工序退回主实体_默认表参照_gxth_gxthMaster',null,null,null,null,null,'1001A11LCP000002UKFR',null,'wsh/refer/gxth/gxthMasterDefaultGridRef/index',null,null,null,null,'gxth','gxth',null,null,'2023-07-28 15:06:25',0 ) 
/

