insert into BD_REFINFO ( CODE,ISTREELAZYLOAD,ISNEEDPARA,ISSPECIALREF,LAYER,REFTYPE,METADATANAMESPACE,METADATATYPENAME,MOBILEREFPATH,MODULENAME,NAME,PARA1,PARA2,PARA3,PK_COUNTRY,PK_INDUSTRY,PK_REFINFO,REFCLASS,REFPATH,REFSYSTEM,RESERV1,RESERV2,RESERV3,RESID,RESIDPATH,WHEREPART,WORKFLOWCONDITIONUSEUNITORG,TS,DR ) values  ( '80H34001','N',null,null,null,0,'clqr','clqrMaster',null,'wsh','材料确认_材料确认主实体_默认表参照_clqr_clqrMaster',null,null,null,null,null,'1001A11LCP000002SBB4',null,'wsh/refer/clqr/clqrMasterDefaultGridRef/index',null,null,null,null,'clqr','clqr',null,null,'2023-07-27 10:49:51',0 ) 
/

