insert into BD_REFINFO ( CODE,ISTREELAZYLOAD,ISNEEDPARA,ISSPECIALREF,LAYER,REFTYPE,METADATANAMESPACE,METADATATYPENAME,MOBILEREFPATH,MODULENAME,NAME,PARA1,PARA2,PARA3,PK_COUNTRY,PK_INDUSTRY,PK_REFINFO,REFCLASS,REFPATH,REFSYSTEM,RESERV1,RESERV2,RESERV3,RESID,RESIDPATH,WHEREPART,WORKFLOWCONDITIONUSEUNITORG,TS,DR ) values  ( '80H330','N',null,null,null,0,'scll','scllMaster',null,'wsh','生产领料_生产领料主实体_默认表参照_scll_scllMaster',null,null,null,null,null,'1001A11LCP000002RWCE',null,'wsh/refer/scll/scllMasterDefaultGridRef/index',null,null,null,null,'scll','scll',null,null,'2023-07-27 08:45:06',0 ) 
/

