insert into BD_REFINFO ( CODE,ISTREELAZYLOAD,ISNEEDPARA,ISSPECIALREF,LAYER,REFTYPE,METADATANAMESPACE,METADATATYPENAME,MOBILEREFPATH,MODULENAME,NAME,PARA1,PARA2,PARA3,PK_COUNTRY,PK_INDUSTRY,PK_REFINFO,REFCLASS,REFPATH,REFSYSTEM,RESERV1,RESERV2,RESERV3,RESID,RESIDPATH,WHEREPART,WORKFLOWCONDITIONUSEUNITORG,TS,DR ) values  ( '80H24001','N',null,null,null,0,'wxrk','wxrkMaster',null,'wsh','外协入库_外协入库主实体_默认表参照_wxrk_wxrkMaster',null,null,null,null,null,'1001ZZ1LCP000001XG9V',null,'wsh/refer/wxrk/wxrkMasterDefaultGridRef/index',null,null,null,null,'wxrk','wxrk',null,null,'2023-07-18 15:08:09',0 ) 
/

