insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9A','wxrkMaster_Add_Group','',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',1,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9B','Add','新增',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',2,'general_btn','common','wxrkMaster_Add_Group',null,'Ctrl+/','button_main',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9C','Edit','修改',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',3,'general_btn','common','wxrkMaster_Add_Group',null,'Alt+P','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9D','Copy','复制',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',4,'general_btn','common','wxrkMaster_Add_Group',null,'Alt+C','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9E','Delete','删除',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',5,'general_btn','common','wxrkMaster_Add_Group',null,'Ctrl+Del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9F','wxrkMaster_Save_Group','',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',6,'buttongroup','common',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9G','Save','保存',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',7,'general_btn','common','wxrkMaster_Save_Group',null,'Ctrl+S','button_main',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9H','SaveAdd','保存新增',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',8,'general_btn','common','wxrkMaster_Save_Group',null,'Alt+S','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9I','Cancel','取消',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',9,'general_btn','common',null,null,'Alt+Q','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9J','wxrkSlave0_AddLine_Group','',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',10,'buttongroup','wxrkSlave0Sub',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9K','wxrkSlave0Sub_AddLine','增行',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',11,'general_btn','wxrkSlave0Sub','wxrkSlave0_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9L','wxrkSlave0Sub_CopyLine','复制',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',12,'general_btn','wxrkSlave0Sub','wxrkSlave0_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9M','wxrkSlave0Sub_DelLine','删行',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',13,'general_btn','wxrkSlave0Sub','wxrkSlave0_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9N','wxrkSlave0_Past_Group','',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',14,'buttongroup','wxrkSlave0Sub',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9O','wxrkSlave0Sub_PastEndLine','粘贴到末行',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',15,'general_btn','wxrkSlave0Sub','wxrkSlave0_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9P','wxrkSlave0Sub_CopyCancelLine','取消',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',16,'general_btn','wxrkSlave0Sub','wxrkSlave0_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9Q','wxrkSlave0Sub_DelLineOpr','删除',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',17,'general_btn','wxrkSlave0SubOpr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9R','wxrkSlave0Sub_ExpandLineOpr','展开',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',18,'general_btn','wxrkSlave0SubOpr',null,null,'f4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9S','wxrkSlave0Sub_CopyLineOpr','复制行',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',19,'general_btn','wxrkSlave0SubOpr',null,null,'Alt+C','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9T','wxrkSlave0Sub_PastNextLineOpr','粘贴至此',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',20,'general_btn','wxrkSlave0SubOpr',null,null,'alt+v','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001ZZ1LCP000001XG9U','Refresh','',null,null,'1001ZZ1000000001XG0Z',null,'Y','80H24001_wxrkMaster',21,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

