insert into BD_REFINFO ( CODE,ISTREELAZYLOAD,ISNEEDPARA,ISSPECIALREF,LAYER,REFTYPE,METADATANAMESPACE,METADATATYPENAME,MOBILEREFPATH,MODULENAME,NAME,PARA1,PARA2,PARA3,PK_COUNTRY,PK_INDUSTRY,PK_REFINFO,REFCLASS,REFPATH,REFSYSTEM,RESERV1,RESERV2,RESERV3,RESID,RESIDPATH,WHEREPART,WORKFLOWCONDITIONUSEUNITORG,TS,DR ) values  ( '80H55001','N',null,null,null,0,'dbsq','dbsqMaster',null,'wsh','调拨申请单_主实体_默认表参照_dbsq_dbsqMaster',null,null,null,null,null,'1001A11LCP000002ETGU',null,'wsh/refer/dbsq/dbsqMasterDefaultGridRef/index',null,null,null,null,'dbsq','dbsq',null,null,'2023-07-21 10:14:12',0 ) 
/

